### ISSUE TITLE
Get-DynDnsRecord - Retrieve full zone tree when Node not provided using RecordType as filter

### ISSUE THREAD

**Issue by jonimcglade** [thedavecarroll/PoShDynDnsApi#11]
**Describe the bug**
When I run **Get-DynDnsRecord -zone <ZONE> -RecordType CNAME** it doesn't pull down the CNAME records for the domain, however when I run as **-RecordType All** the CNAME records do appear.

**To Reproduce**
Get-DynDnsRecord -zone spenceandpartners.co.uk -RecordType CNAME > Blank Output
Get-DynDnsRecord -zone spenceandpartners.co.uk -RecordType All > Contains CNAME Records

**Expected behavior**
I would expect that the CNAME records come down when called explicitly.

**Screenshots**
![image](https://user-images.githubusercontent.com/45765830/89645215-3e0be780-d8b1-11ea-908d-9250625eb407.png)

**PowerShell Environment (please complete the following information):**
 - OS: Windows 10
 - Edition Desktop
 - Version 2004
- Powershell : 5.1

**Comment by thedavecarroll** [comment]
Thank you for submitting an issue! So glad to see that someone is using this module.

I've taken a look and can confirm that, without using the `Node` parameter, nothing is returned.

There are two hidden properties that can help us track down the problem, `RawData` and `RecordId`.

```powershell
Get-DynDnsRecord -Zone anovelidea.org -RecordType All | Where-Object {$_.Type -eq 'CNAME'} | Get-Member -MemberType Property -Force
```
```text
   TypeName: DynDnsRecord_CNAME

Name     MemberType Definition                 
----     ---------- ----------                 
Name     Property   string Name {get;set;}     
NameHost Property   string NameHost {get;set;} 
RawData  Property   psobject RawData {get;set;}
RecordId Property   string RecordId {get;set;} 
TTL      Property   int TTL {get;set;}         
Type     Property   string Type {get;set;}     
Zone     Property   string Zone {get;set;} 
```

Here is the `Get-DynDnsRecord` output with those included.

```powershell
Get-DynDnsRecord -Zone anovelidea.org -RecordType All | Where-Object {$_.Type -eq 'CNAME'} | Format-List RawData,RecordId,*
```
```text
RawData  : @{zone=anovelidea.org; ttl=3600; fqdn=www2.anovelidea.org; record_type=CNAME; rdata=; record_id=413975608}
RecordId : 413975608
NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www2.anovelidea.org
Type     : CNAME
TTL      : 3600

RawData  : @{zone=anovelidea.org; ttl=3600; fqdn=www3.anovelidea.org; record_type=CNAME; rdata=; record_id=413975609}
RecordId : 413975609
NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www3.anovelidea.org
Type     : CNAME
TTL      : 3600
```

In the `RawData` property, we can see the `fqdn` for each of the records; this data is mapped to the public `Name` property. Note that they are actually nodes under the root domain.

The `Get-DynDnsRecord` prepends the `Node` input to the `Zone` input, and if it is not provided, defaults to using the `Zone` as the `Node`. The URI is built using this: `"/REST/$($RecordType)Record/$Zone/$Fqdn/"`.

Since `CNAME` records are not allowed at the root, a call to `/REST/CNAMERecord/<zone>/<zone>` will return the following:

```json
{
  "status": "success",
  "data": [],
  "job_id": 0,
  "msgs": [
    {
      "INFO": "detail: Found 0 records",
      "SOURCE": "API-B",
      "ERR_CD": null,
      "LVL": "INFO"
    }
  ]
}
```

With the default `RecordType` of **All**, it uses URI `/REST/AllRecord/<zone>` or `/REST/AllRecord/<zone>/<node>` which "[r]etrieves a list of all record resources for the specified node and zone combination **as well as all records from any object below that point on the zone hierarchy**". The **bold** text is the key difference between any other `RecordType` URI. Here is the [Get All Records (API)](https://help.dyn.com/get-all-records-api/) documentation page.

So `Get-DynDnsRecord -RecordType All -Zone $Zone` should retrieve all records in the domain, regardless of type or the location of the records position in the hierarchy.

This behavior should be consistent with all other `RecordType` values, _CNAME_, _A_, _MX_, etc.

There are a few ways to handle this behavior.

## Option 1 - Get-DynDnsRecord and Where-Object

```powershell
Get-DynDnsRecord -Zone anovelidea.org -RecordType All | Where-Object {$_.Type -eq 'CNAME'}
```

You can assign the output to a variable or add a pipeline after the where clause to do whatever processing you need.

## Option 2- Get-DynDnsNodeList

```powershell
$Zone = 'anovelidea.org'; Get-DynDnsNodeList -Zone $Zone | ForEach-Object { '-'*40; $_ ; Get-DynDnsRecord -RecordType CNAME -Zone $Zone -Node ($_.Replace(".$Zone",''))}
```
```text
----------------------------------------
anovelidea.org
----------------------------------------
redirect.anovelidea.org
----------------------------------------
subtest.anovelidea.org
----------------------------------------
www.anovelidea.org
----------------------------------------
www2.anovelidea.org
NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www2.anovelidea.org
Type     : CNAME
TTL      : 3600

----------------------------------------
www3.anovelidea.org
NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www3.anovelidea.org
Type     : CNAME
TTL      : 3600
```

You can replace the contents of the `ForEach-Object` clause with whatever processing code you need.

## Option 3 - Get-DynDnsRecord

```powershell
$AllRecords = Get-DynDnsRecord -Zone anovelidea.org -RecordType All
$AllRecords | Group-Object -Property Type | ForEach-Object { '-'* 40; 'RecordType: {0}{1}' -f $_.Name,[System.Environment]::NewLine; $_.Group }
```
```text
----------------------------------------
RecordType: CNAME

NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www2.anovelidea.org
Type     : CNAME
TTL      : 3600

NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www3.anovelidea.org
Type     : CNAME
TTL      : 3600

----------------------------------------
RecordType: SOA

Administrator          : powershell.anovelidea.org.
SerialNumber           : 2019070414
PrimaryServer          : ns1.p01.dynect.net.
TimeToExpiration       : 604800
TimeToZoneFailureRetry : 600
TimeToZoneRefresh      : 3600
DefaultTTL             : 1800
Zone                   : anovelidea.org
Name                   : anovelidea.org
Type                   : SOA
TTL                    : 3600

----------------------------------------
RecordType: NS

NameHost      : ns1.p01.dynect.net.
Authoritative : Primary
Zone          : anovelidea.org
Name          : anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns2.p01.dynect.net.
Authoritative : Primary
Zone          : anovelidea.org
Name          : anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns3.p01.dynect.net.
Authoritative : Primary
Zone          : anovelidea.org
Name          : anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns4.p01.dynect.net.
Authoritative : Primary
Zone          : anovelidea.org
Name          : anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns1.p01.dynect.net.
Authoritative : 
Zone          : anovelidea.org
Name          : subtest.anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns2.p01.dynect.net.
Authoritative : 
Zone          : anovelidea.org
Name          : subtest.anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns3.p01.dynect.net.
Authoritative : 
Zone          : anovelidea.org
Name          : subtest.anovelidea.org
Type          : NS
TTL           : 86400

NameHost      : ns4.p01.dynect.net.
Authoritative : 
Zone          : anovelidea.org
Name          : subtest.anovelidea.org
Type          : NS
TTL           : 86400

----------------------------------------
RecordType: A

Address : 172.217.3.243
Zone    : anovelidea.org
Name    : www.anovelidea.org
Type    : A
TTL     : 3600
```

You can replace the contents of the `ForEach-Object` clause with whatever processing code you need.

## Note

You can see the URI for each API call by reviewing the output of `Get-DynDnsHistory`.
The module variable that stores the call history will clear when the module is unloaded or the PowerShell session ends.

From the output, you can also see that `Get-DynDnsRecord` calls will iterate through if multiple records are returned. As stated before, this data can also be found in the `RawData` hidden property.

Sample call for `Get-DynDnsRecord -RecordType All -Zone anovelidea.org`.

```json
{
  "status": "success",
  "data": [
    "/REST/CNAMERecord/anovelidea.org/www2.anovelidea.org/413975608",
    "/REST/CNAMERecord/anovelidea.org/www3.anovelidea.org/413975609",
    "/REST/SOARecord/anovelidea.org/anovelidea.org/411854876",
    "/REST/NSRecord/anovelidea.org/anovelidea.org/411854868",
    "/REST/NSRecord/anovelidea.org/anovelidea.org/411854869",
    "/REST/NSRecord/anovelidea.org/anovelidea.org/411854870",
    "/REST/NSRecord/anovelidea.org/anovelidea.org/411854871",
    "/REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829806",
    "/REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829807",
    "/REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829808",
    "/REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829809",
    "/REST/ARecord/anovelidea.org/www.anovelidea.org/411855619"
  ],
  "job_id": 3790631296,
  "msgs": [
    {
      "INFO": "get_tree: Here is your zone tree",
      "SOURCE": "BLL",
      "ERR_CD": null,
      "LVL": "INFO"
    }
  ]
}
```

Sample call for `Get-DynDnsRecord -RecordType CNAME-Zone anovelidea.org -Node www2`.

```json
{
  "status": "success",
  "data": [
    "/REST/CNAMERecord/anovelidea.org/www2.anovelidea.org/413975608"
  ],
  "job_id": 3790633945,
  "msgs": [
    {
      "INFO": "get_tree: Here is your zone tree",
      "SOURCE": "BLL",
      "ERR_CD": null,
      "LVL": "INFO"
    }
  ]
}
```

## Conclusion

Based on my findings, I believe the behavior you discovered is consistent with the Dyn DNS API design. My implementation of accessing their resources may have muddied the water a little. If so, my apologies.

Please note that I will be closing the issues that I opened, as I won't be extending the functionality of this module.

If you have any issues with the current commands, **please continue to raise them**. I'm still paying for my developer account with Dyn/Oracle so I should be able to provide fixes.

Also, feel free to give me a follow on Twitter [@thedavecarroll](https://twitter.com/thedavecarroll).

I used [Insomnia Core](https://insomnia.rest/download/core/?) to do my testing.

<img width="798" alt="DynDnsGetAllRecord" src="https://user-images.githubusercontent.com/37391437/89684117-67337480-d8bf-11ea-8637-cb6760a79869.png">

**Comment by thedavecarroll** [comment]
I've had some time to think about this and consulted with a developer friend.

The default behavior of `Get-DynDnsRecord` should be changed to return all records if a `Node` is not provided. The `RecordType` will be used to filter all records in the data returned from the first call.

Give me a few days and I can provide an update to the module.

**Comment by jonimcglade** [comment]
Thanks Dave,

Option 1 above would suffice I think for my purposes. The module you have written it great, it's just unfortunate that we're using it to extract the data & migrate to another DNS provider as DYN is closing down. I've been able to combine it with some powershell to extract all the records for all domains into JSON & then we can use this to populate the new provider via code. Let me know when you get the module updated and I'll have a test with it.

Cheers.

**Comment by thedavecarroll** [comment]
I have updated the module to `0.1.2` in the PSGallery.

You should be able to download it via using the following:
```powershell
Update-Module -Name PoShDynDnsAPI
```

`Get-DynDnsRecord` now has the following behavior:
- If Node is not provided:
  - Return the entire zone tree, but filter on RecordType for all records.
- If Node is provided:
  - Return records contained in the node and filter on RecordType.

Example
```powershell
Get-DynDnsRecord -Zone anovelidea.org -RecordType CNAME -Verbose
```

```text
VERBOSE: API-3.7.16 : INFO : BLL : isalive: User session is still active
VERBOSE: No node provided. CNAME record types for zone tree will be returned.
VERBOSE: API-3.7.16 : INFO : BLL : get_tree: Here is your zone tree
VERBOSE: API-3.7.16 : INFO : API-B : get: Found the record

NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www2.anovelidea.org
Type     : CNAME
TTL      : 3600

VERBOSE: API-3.7.16 : INFO : API-B : get: Found the record
NameHost : www.anovelidea.org.
Zone     : anovelidea.org
Name     : www3.anovelidea.org
Type     : CNAME
TTL      : 3600

VERBOSE: Skipping /REST/SOARecord/anovelidea.org/anovelidea.org/411854876 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/anovelidea.org/411854868 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/anovelidea.org/411854869 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/anovelidea.org/411854870 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/anovelidea.org/411854871 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829806 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829807 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829808 due to RecordType
VERBOSE: Skipping /REST/NSRecord/anovelidea.org/subtest.anovelidea.org/415829809 due to RecordType
VERBOSE: Skipping /REST/ARecord/anovelidea.org/www.anovelidea.org/411855619 due to RecordType
```
I hope this behavior is more helpful.

Please let me know how it works out for you.

Thanks,
Dave

**Comment by jonimcglade** [comment]
Thanks Dave,

Did the module update & it works a treat, returns the CNAME records fine now.

Cheers,
Joni.

**Comment by thedavecarroll** [comment]
Hey, @jonimcglade 
Just wanted to let you know I wrote [an article](https://bit.ly/3ayBbFt) about how I responded to this issue in case you want to read it.

Thanks again for using the module and helping to make it better through submitting issues.

Dave
